services:
  backend:
    build: ./backend
    container_name: smart_task_backend
    ports:
      - "8000:8000"
      - "8089:8089"
    volumes:
      - ./backend:/code
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: smart_task_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart_tasks
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: smart_task_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: